export const ENVELOPES_TOKENS = {
  ENVELOPE_REPOSITORY: Symbol("ENVELOPE_REPOSITORY"),
  ACCOUNT_REPOSITORY: Symbol("ACCOUNT_REPOSITORY"),
  TRANSACTION_REPOSITORY: Symbol("TRANSACTION_REPOSITORY"),
  BALANCE_REPOSITORY: Symbol("BALANCE_REPOSITORY"),
} as const;
