export const REPORTS_TOKENS = {
  TRANSACTION_REPOSITORY: Symbol("REPORTS_TRANSACTION_REPOSITORY"),
  ACCOUNT_REPOSITORY: Symbol("REPORTS_ACCOUNT_REPOSITORY"),
  CATEGORY_REPOSITORY: Symbol("REPORTS_CATEGORY_REPOSITORY"),
  CATEGORY_GROUP_REPOSITORY: Symbol("REPORTS_CATEGORY_GROUP_REPOSITORY"),
} as const;
