export const TRANSACTIONS_TOKENS = {
  TRANSACTION_REPOSITORY: Symbol("TRANSACTION_REPOSITORY"),
  CATEGORY_REPOSITORY: Symbol("CATEGORY_REPOSITORY"),
  ACCOUNT_REPOSITORY: Symbol("ACCOUNT_REPOSITORY"),
} as const;
